[default]
DEBUG = true
SECRET_KEY = 'Desenvolvedor Python'
UPLOAD_FOLDER = 'app/static/img'
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:1234@localhost/ruifma'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    'app.resources.admin:init_app',
    'app.db:init_app'
]